
parameters:
    database_host: blog-symfony.cp98ffmtxieu.eu-west-1.rds.amazonaws.com
    database_port: 3306
    database_name: projet_symfony
    database_user: master
    database_password: mastercraft
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    secret: 0217a7df7df13f1e51c806a22e651122f5089fb1
