# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        blog_users:
            entity:
                class: BlogBundle:User
                property: username

    encoders:
        BlogBundle\Entity\User: plaintext

    role_hierarchy:
        REVIEWER: READER

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        blog:
            pattern: ^/(logout|login_check|articles|themes|admin)
            form_login:
                login_path: /login
                check_path: /login_check
            logout:
                path: /logout
                target: /a
