# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        blog_users:
            entity:
                class: BlogBundle:User
                property: username

    encoders:
        BlogBundle\Entity\User: plaintext

    role_hierarchy:
        ROLE_REVIEWER: ROLE_READER

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js|node_modules)/
            security: false

        login:
            pattern: ^/login$
            anonymous: ~

        blog:
            pattern: ^/(logout|login_check|articles|themes|admin|comments|reports)?
            provider: blog_users
            form_login:
                login_path: /login
                check_path: /login_check
                default_target_path: /
            logout:
                path: /logout
                target: /

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }

        - { path: ^/articles$, role: [ROLE_WRITER, ROLE_READER] }
        - { path: ^/articles/(add|edit), role: ROLE_WRITER }
        - { path: ^/articles/delete, role: [ROLE_WRITER, ROLE_ADMIN] }
        - { path: ^/articles/(read|unread), role: [ROLE_READER] }
        - { path: ^/articles/reports/add, role: [ROLE_READER] }

        - { path: ^/themes/read, role: [ROLE_READER] }
        - { path: ^/themes/review, role: [ROLE_REVIEWER] }

        - { path: ^/comments/$, role: [ROLE_REVIEWER] }
        - { path: ^/comments/(add/edit), role: [ROLE_REVIEWER] }
        - { path: ^/comments/delete, role: [ROLE_REVIEWER, ROLE_ADMIN] }
        - { path: ^/comments/report/add, role: [ROLE_READER, ROLE_WRITER] }

        - { path: ^/reports/$, role: [ROLE_READER, ROLE_WRITER] }xs