<?php

namespace BlogBundle\Repository;

/**
 * ReportingCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReportingCommentRepository extends \Doctrine\ORM\EntityRepository
{
}
