<?php

namespace BlogBundle\Repository;

/**
 * ReportingArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReportingArticleRepository extends \Doctrine\ORM\EntityRepository
{
}
