<?php

namespace BlogBundle\Repository;

/**
 * UserThemeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserThemeRepository extends \Doctrine\ORM\EntityRepository
{
}
