blog_homepage:
    path:     /
    defaults: { _controller: BlogBundle:Default:index }

login:
    path:     /login
    defaults: { _controller: BlogBundle:Security:login }

login_check:
    path: /login_check

logout:
    path: /logout

article_index:
    path:     /articles
    defaults: { _controller: BlogBundle:Articles:index }
