blog_homepage:
    path:     /
    defaults: { _controller: BlogBundle:Default:index }

login:
    path:     /login
    defaults: { _controller: BlogBundle:Security:login }

login_check:
    path: /login_check

logout:
    path: /logout

article_list:
    path:     /articles
    defaults: { _controller: BlogBundle:Articles:list }

article_show:
    path:     /articles/{id}
    requirements:
        id: '\d+'
    defaults: { _controller: BlogBundle:Articles:show }

user_list:
  path: /admin/users
  defaults: { _controller: BlogBundle:Users:list }

admin_user_edit:
  path: /admin/users/{id}
  defaults: { _controller: BlogBundle:Users:edit }

admin_user_edit_suite:
  path: /admin/usersSuite/{id}
  defaults: { _controller: BlogBundle:Users:edit }

choose_theme:
    path:     /chooseTheme
    defaults: { _controller: BlogBundle:Themes:chooseTheme }
