# ######## #
# HOMEPAGE #
# ######## #
blog_homepage:
    path:     /
    defaults: { _controller: BlogBundle:Default:index }

# ESSENTIAL THINGS
login:
    path:     /login
    defaults: { _controller: BlogBundle:Security:login }

login_check:
    path: /login_check

logout:
    path: /logout


# ################## #
# ARTICLES RELATIVES #
# ################## #
article_list:
    path:     /articles
    defaults: { _controller: BlogBundle:Articles:list }

article_show:
    path:     /articles/{id}
    requirements:
        id: '\d+'
    defaults: { _controller: BlogBundle:Articles:show }

article_add:
    path:     /articles/add
    defaults: { _controller: BlogBundle:Articles:add }

article_edit:
    path: /articles/edit/{id}
    requirements:
        id: \d{1,2}
    defaults: { _controller: BlogBundle:Articles:edit }

article_edit_next:
    path: /articles/edit/{id}/next
    requirements:
        id: \d{1,2}
    methods: POST
    defaults: { _controller: BlogBundle:Articles:editNext }

article_delete:
  path: /articles/delete/{id}
  defaults: { _controller: BlogBundle:Articles:delete }

article_report:
    path: /articles/report/{id}
    defaults: { _controller: BlogBundle:Articles:report }

article_read:
    path: /articles/read/{id}
    defaults: { _controller: BlogBundle:Articles:read }

article_unread:
    path: /articles/unread/{id}
    defaults: { _controller: BlogBundle:Articles:unread }

# ################## #
# COMMENTS RELATIVES #
# ################## #
comment_add:
    path:     /comments/add/{articleId}
    requirements:
        articleId: '\d+'
    methods: [POST]
    defaults: { _controller: BlogBundle:Comments:add }

comment_edit:
    path: /comments/edit/{commentId}
    requirements:
        commentId: '\d+'
    methods: [POST]
    defaults: { _controller: BlogBundle:Comments:modify }

comment_delete:
    path:   /comments/delete/{commentId}
    requirements:
        commentId: '\d+'
    defaults: { _controller: BlogBundle:Comments:delete }

comment_list:
    path: /comments
    defaults: { _controller: BlogBundle:Comments:list }

comment_add_report:
    path: /comment/report/add/{id}
    defaults: { _controller: BlogBundle:Comments:report }

# ################ #
# THEMES RELATIVES #
# ################ #
theme_list_read:
    path: /themes/read
    defaults: { _controller: BlogBundle:Themes:listRead }

theme_list_review:
    path: /themes/review
    defaults: { _controller: BlogBundle:Themes:listReview }

theme_delete_read:
    path: /themes/read/delete/{themeId}
    requirements:
        themeId: '\d+'
    defaults: { _controller: BlogBundle:Themes:deleteRead }

theme_delete_review:
    path: /themes/review/delete/{themeId}
    requirements:
        themeId: '\d+'
    defaults: { _controller: BlogBundle:Themes:deleteReview }

## KESAKO
article_list_by_author:
  path: /articles/perso/
  defaults: { _controller: BlogBundle:Articles:listByAuthor }

# ####################### #
# ADMINISTRATOR RELATIVES #
# ####################### #

# ADMIN & USERS
admin_user_list:
    path: /admin/users
    defaults: { _controller: BlogBundle:Users:list }

admin_user_add:
    path: /admin/users/add
    defaults: { _controller: BlogBundle:Users:add }

admin_user_edit:
    path: /admin/users/edit/{id}
    requirements:
        id: \d{1,2}
    defaults: { _controller: BlogBundle:Users:edit }

admin_user_edit_next:
    path: /admin/users/edit/{id}/next
    methods: [POST]
    defaults: { _controller: BlogBundle:Users:editNext }

admin_user_delete:
    path: /admin/users/delete/{id}
    defaults: { _controller: BlogBundle:Users:delete }

# ADMIN & THEMES
admin_theme_list:
  path: /admin/themes
  defaults: { _controller: BlogBundle:Themes:list }

admin_theme_add:
  path: /admin/themes/add
  defaults: { _controller: BlogBundle:Themes:add }

admin_theme_delete:
  path: /admin/themes/delete/{id}
  defaults: { _controller: BlogBundle:Themes:delete }

# ADMIN & REPORTING
admin_reporting_article_list:
  path: /admin/reporting/articles
  defaults: { _controller: BlogBundle:ReportingArticle:list }

admin_reporting_comment_list:
  path: /admin/reporting/comment
  defaults: { _controller: BlogBundle:ReportingComment:list }

admin_reporting_article_delete:
  path: /admin/reporting/{id}
  defaults: { _controller: BlogBundle:ReportingArticle:deleteAdmin }

# REPORTING ARTICLE RELATIVES
reporting_list:
  path: /reports
  defaults: { _controller: BlogBundle:ReportingArticle:listPerso }

reporting_article_show:
  path: /report/articles/{id}
  defaults: { _controller: BlogBundle:ReportingArticle:delete }

reporting_comments_show:
  path: /report/articles/{id}
  defaults: { _controller: BlogBundle:ReportingArticle:delete }

