# HOMEPAGE
blog_homepage:
    path:     /
    defaults: { _controller: BlogBundle:Default:index }

# ESSENTIAL THINGS
login:
    path:     /login
    defaults: { _controller: BlogBundle:Security:login }

login_check:
    path: /login_check

logout:
    path: /logout


# ARTICLE RELATIVES
article_list:
    path:     /articles
    defaults: { _controller: BlogBundle:Articles:list }

article_show:
    path:     /articles/{id}
    requirements:
        id: '\d+'
    defaults: { _controller: BlogBundle:Articles:show }

article_add:
    path:     /articles/add
    defaults: { _controller: BlogBundle:Articles:add }

article_edit:
  path: /articles/modifier/{id}
  defaults: { _controller: BlogBundle:Articles:edit }
  requirements:
    id: \d{1,2}

article_edit_suite:
  path: /articles/modifierSuite/{id}
  defaults: { _controller: BlogBundle:Articles:editSuite }
  requirements:
    _method: POST

article_delete:
  path: /articles/delete/{id}
  defaults: { _controller: BlogBundle:Articles:delete }

article_add2:
    path:     /articles/{title}/{content}/{createdAt}/{author}/{themes}
    defaults: { _controller: BlogBundle:Articles:add2 }

article_add3:
    path:     /articles/add3
    defaults: { _controller: BlogBundle:Articles:add3 }

article_signaler:
    path: /articles/signaler/{id}
    defaults: { _controller: BlogBundle:Articles:signaler }

comment_add:
    path:     /comments/add/{articleId}
    requirements:
        articleId: '\d+'
    methods: [POST]
    defaults: { _controller: BlogBundle:Comment:add }

comment_delete:
    path:   /comments/delete/{commentId}
    requirements:
        commentId: '\d+'
    defaults: { _controller: BlogBundle:Comment:delete }

comment_signaler:
    path: /comment/signaler/{id}
    defaults: { _controller: BlogBundle:Comment:signalerComment }

# ADMIN RELATIVES
admin_user_list:
  path: /admin/users
  defaults: { _controller: BlogBundle:Users:list }

admin_user_edit:
  path: /admin/users/{id}
  defaults: { _controller: BlogBundle:Users:edit }
  requirements:
    id: \d{1,2}

admin_user_edit_suite:
  path: /admin/usersSuite/{id}
  defaults: { _controller: BlogBundle:Users:editSuite }
  requirements:
    _method: POST

admin_user_ajouter:
  path: /admin/users/new
  defaults: { _controller: BlogBundle:Users:ajouter }

admin_user_delete:
  path: /admin/users/delete/{id}
  defaults: { _controller: BlogBundle:Users:delete }

admin_theme_list:
  path: /admin/themes
  defaults: { _controller: BlogBundle:Themes:list }

admin_theme_ajouter:
  path: /admin/themes/new
  defaults: { _controller: BlogBundle:Themes:ajouter }

admin_theme_delete:
  path: /admin/themes/delete/{id}
  defaults: { _controller: BlogBundle:Themes:delete }

admin_reportingarticle_list:
  path: /admin/reporting/articles/
  defaults: { _controller: BlogBundle:ReportingArticle:list }

admin_reportingcomment_list:
  path: /admin/reporting/comment/
  defaults: { _controller: BlogBundle:ReportingComment:list }

admin_reportingarticle_test:
  path: /admin/reporting/articles/test
  defaults: { _controller: BlogBundle:ReportingArticle:test }

# REPORTING ARTICLE RELATIVES
reporting_listePerso :
  path: /reports/
  defaults: { _controller: BlogBundle:ReportingArticle:listPerso }

deleteReportArticle_listPerso :
  path: /report/articles/{id}
  defaults: { _controller: BlogBundle:ReportingArticle:delete }

deleteReportComment_listPerso :
  path: /report/articles/{id}
  defaults: { _controller: BlogBundle:ReportingArticle:delete }

# THEME RELATIVES
choose_theme:
    path:     /chooseTheme
    defaults: { _controller: BlogBundle:Themes:chooseTheme }


