BlogBundle\Entity\Comment:
    type: entity
    table: null
    repositoryClass: BlogBundle\Repository\CommentRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        content:
            type: text
        note:
            type: smallint
        createdAt:
            type: datetime
            column: created_at
        modifiedAt:
            type: datetime
            column: modified_at

    manyToOne:
        author:
            targetEntity: BlogBundle\Entity\User

        article:
            targetEntity: BlogBundle\Entity\Article
            inversedBy: comments

    lifecycleCallbacks:
        prePersist: [setCreatedAtInitialValue, setUpdatedAtValue]
        preFlush: [setUpdatedAtValue]