BlogBundle\Entity\ReportingComment:
    type: entity
    table: null
    repositoryClass: BlogBundle\Repository\ReportingCommentRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    manyToOne:
        user:
            targetEntity: BlogBundle\Entity\User
            inversedBy: reportingsComment
        comment:
            targetEntity: BlogBundle\Entity\Comment
            inversedBy: reportings


    lifecycleCallbacks: {  }
