BlogBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: BlogBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        username:
            type: string
            length: 255
            unique: true
        password:
            type: string
            length: 255

    manyToMany:
        roles:
            targetEntity: BlogBundle\Entity\Role
            inversedBy: users

        readArticles:
            targetEntity: BlogBundle\Entity\Article
            inversedBy: readBy

    oneToMany:
        writenArticles:
            targetEntity: BlogBundle\Entity\Article
            mappedBy: author
            orphanRemoval: true
            cascade: [ remove ]

        themes:
            targetEntity: BlogBundle\Entity\UserTheme
            mappedBy: user
            orphanRemoval: true
            cascade: [ remove ]

        comments:
            targetEntity: BlogBundle\Entity\Comment
            mappedBy: author
            orphanRemoval: true
            cascade: [ remove ]

        reportingsArticle:
            targetEntity: BlogBundle\Entity\ReportingArticle
            mappedBy: user
            orphanRemoval: true
            cascade: [ remove ]
            fetch: EXTRA_LAZY

        reportingsComment:
            targetEntity: BlogBundle\Entity\ReportingComment
            mappedBy: user
            orphanRemoval: true
            cascade: [ remove ]
            fetch: EXTRA_LAZY

    lifecycleCallbacks: {  }
